/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditPanel.java
 *
 * Created on 2011-05-28, 19:38:45
 */
package GUI;

import Basic.Grid;
import ewakuacja.EwakuacjaView;

/**
 *
 * @author DSidor
 */
public class EditPanel extends javax.swing.JPanel {

    /** Creates new form EditPanel */
    public EditPanel() {
        initComponents();
        initFields();
    }

    private void initFields() {
        emptyColorPanel.setBackground(CellColors.getMapColor(Grid.EMPTY));
        wallColorPanel.setBackground(CellColors.getMapColor(Grid.WALL));
        obstacleColorPanel.setBackground(CellColors.getMapColor(Grid.OBSTACLE));
        exitColorPanel.setBackground(CellColors.getMapColor(Grid.EXIT));
        personColorPanel.setBackground(CellColors.getMapColor(Grid.PERSON1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cellTypeButtons = new javax.swing.ButtonGroup();
        editingButton = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rowsSpinner = new javax.swing.JSpinner();
        columnsSpinner = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        emptyColorPanel = new javax.swing.JPanel();
        wallColorPanel = new javax.swing.JPanel();
        exitColorPanel = new javax.swing.JPanel();
        personColorPanel = new javax.swing.JPanel();
        obstacleColorPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        emptyCellButton = new javax.swing.JRadioButton();
        wallCellButton = new javax.swing.JRadioButton();
        exitCellButton = new javax.swing.JRadioButton();
        personCellButton = new javax.swing.JRadioButton();
        obstacleCellButton = new javax.swing.JRadioButton();

        setName("Form"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ewakuacja.EwakuacjaApp.class).getContext().getResourceMap(EditPanel.class);
        editingButton.setText(resourceMap.getString("editingButton.text")); // NOI18N
        editingButton.setAlignmentX(0.5F);
        editingButton.setName("editingButton"); // NOI18N
        editingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editingButtonActionPerformed(evt);
            }
        });
        add(editingButton);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 1));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(68, 23));
        jLabel1.setMinimumSize(new java.awt.Dimension(68, 23));
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(68, 23));
        jPanel5.add(jLabel1);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(65, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(65, 23));
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(65, 23));
        jPanel5.add(jLabel2);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 3));
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        rowsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        rowsSpinner.setEnabled(false);
        rowsSpinner.setMaximumSize(new java.awt.Dimension(32767, 23));
        rowsSpinner.setMinimumSize(new java.awt.Dimension(63, 23));
        rowsSpinner.setName("rowsSpinner"); // NOI18N
        rowsSpinner.setPreferredSize(new java.awt.Dimension(63, 23));
        rowsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rowsSpinnerStateChanged(evt);
            }
        });
        jPanel6.add(rowsSpinner);

        columnsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        columnsSpinner.setEnabled(false);
        columnsSpinner.setMaximumSize(new java.awt.Dimension(32767, 23));
        columnsSpinner.setMinimumSize(new java.awt.Dimension(63, 23));
        columnsSpinner.setName("columnsSpinner"); // NOI18N
        columnsSpinner.setPreferredSize(new java.awt.Dimension(63, 23));
        columnsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                columnsSpinnerStateChanged(evt);
            }
        });
        jPanel6.add(columnsSpinner);

        jPanel1.add(jPanel6);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        emptyColorPanel.setMaximumSize(new java.awt.Dimension(23, 23));
        emptyColorPanel.setMinimumSize(new java.awt.Dimension(23, 23));
        emptyColorPanel.setName("emptyColorPanel"); // NOI18N
        emptyColorPanel.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout emptyColorPanelLayout = new javax.swing.GroupLayout(emptyColorPanel);
        emptyColorPanel.setLayout(emptyColorPanelLayout);
        emptyColorPanelLayout.setHorizontalGroup(
            emptyColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        emptyColorPanelLayout.setVerticalGroup(
            emptyColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(emptyColorPanel);

        wallColorPanel.setMaximumSize(new java.awt.Dimension(23, 23));
        wallColorPanel.setMinimumSize(new java.awt.Dimension(23, 23));
        wallColorPanel.setName("wallColorPanel"); // NOI18N
        wallColorPanel.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout wallColorPanelLayout = new javax.swing.GroupLayout(wallColorPanel);
        wallColorPanel.setLayout(wallColorPanelLayout);
        wallColorPanelLayout.setHorizontalGroup(
            wallColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        wallColorPanelLayout.setVerticalGroup(
            wallColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(wallColorPanel);

        exitColorPanel.setMaximumSize(new java.awt.Dimension(23, 23));
        exitColorPanel.setMinimumSize(new java.awt.Dimension(23, 23));
        exitColorPanel.setName("exitColorPanel"); // NOI18N
        exitColorPanel.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout exitColorPanelLayout = new javax.swing.GroupLayout(exitColorPanel);
        exitColorPanel.setLayout(exitColorPanelLayout);
        exitColorPanelLayout.setHorizontalGroup(
            exitColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        exitColorPanelLayout.setVerticalGroup(
            exitColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(exitColorPanel);

        personColorPanel.setMaximumSize(new java.awt.Dimension(23, 23));
        personColorPanel.setMinimumSize(new java.awt.Dimension(23, 23));
        personColorPanel.setName("personColorPanel"); // NOI18N
        personColorPanel.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout personColorPanelLayout = new javax.swing.GroupLayout(personColorPanel);
        personColorPanel.setLayout(personColorPanelLayout);
        personColorPanelLayout.setHorizontalGroup(
            personColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        personColorPanelLayout.setVerticalGroup(
            personColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(personColorPanel);

        obstacleColorPanel.setMaximumSize(new java.awt.Dimension(23, 23));
        obstacleColorPanel.setMinimumSize(new java.awt.Dimension(23, 23));
        obstacleColorPanel.setName("obstacleColorPanel"); // NOI18N
        obstacleColorPanel.setPreferredSize(new java.awt.Dimension(23, 23));

        javax.swing.GroupLayout obstacleColorPanelLayout = new javax.swing.GroupLayout(obstacleColorPanel);
        obstacleColorPanel.setLayout(obstacleColorPanelLayout);
        obstacleColorPanelLayout.setHorizontalGroup(
            obstacleColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        obstacleColorPanelLayout.setVerticalGroup(
            obstacleColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel3.add(obstacleColorPanel);

        jPanel2.add(jPanel3);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        cellTypeButtons.add(emptyCellButton);
        emptyCellButton.setSelected(true);
        emptyCellButton.setText(resourceMap.getString("emptyCellButton.text")); // NOI18N
        emptyCellButton.setEnabled(false);
        emptyCellButton.setMaximumSize(new java.awt.Dimension(32222, 23));
        emptyCellButton.setName("emptyCellButton"); // NOI18N
        emptyCellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyCellButtonActionPerformed(evt);
            }
        });
        jPanel4.add(emptyCellButton);

        cellTypeButtons.add(wallCellButton);
        wallCellButton.setText(resourceMap.getString("wallCellButton.text")); // NOI18N
        wallCellButton.setEnabled(false);
        wallCellButton.setMaximumSize(new java.awt.Dimension(32222, 23));
        wallCellButton.setName("wallCellButton"); // NOI18N
        wallCellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wallCellButtonActionPerformed(evt);
            }
        });
        jPanel4.add(wallCellButton);

        cellTypeButtons.add(exitCellButton);
        exitCellButton.setText(resourceMap.getString("exitCellButton.text")); // NOI18N
        exitCellButton.setEnabled(false);
        exitCellButton.setMaximumSize(new java.awt.Dimension(32222, 23));
        exitCellButton.setName("exitCellButton"); // NOI18N
        exitCellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitCellButtonActionPerformed(evt);
            }
        });
        jPanel4.add(exitCellButton);

        cellTypeButtons.add(personCellButton);
        personCellButton.setText(resourceMap.getString("personCellButton.text")); // NOI18N
        personCellButton.setEnabled(false);
        personCellButton.setMaximumSize(new java.awt.Dimension(32222, 23));
        personCellButton.setName("personCellButton"); // NOI18N
        personCellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personCellButtonActionPerformed(evt);
            }
        });
        jPanel4.add(personCellButton);

        cellTypeButtons.add(obstacleCellButton);
        obstacleCellButton.setText(resourceMap.getString("obstacleCellButton.text")); // NOI18N
        obstacleCellButton.setEnabled(false);
        obstacleCellButton.setMaximumSize(new java.awt.Dimension(32222, 23));
        obstacleCellButton.setName("obstacleCellButton"); // NOI18N
        obstacleCellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obstacleCellButtonActionPerformed(evt);
            }
        });
        jPanel4.add(obstacleCellButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void emptyCellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyCellButtonActionPerformed
        cellTypeSelected = Grid.EMPTY;
    }//GEN-LAST:event_emptyCellButtonActionPerformed

    private void wallCellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wallCellButtonActionPerformed
        cellTypeSelected = Grid.WALL;
    }//GEN-LAST:event_wallCellButtonActionPerformed

    private void exitCellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitCellButtonActionPerformed
        cellTypeSelected = Grid.EXIT;
    }//GEN-LAST:event_exitCellButtonActionPerformed

    private void personCellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personCellButtonActionPerformed
        cellTypeSelected = Grid.PERSON1;
    }//GEN-LAST:event_personCellButtonActionPerformed

    private void editingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editingButtonActionPerformed
        boolean enable = editingButton.isSelected();
        if (enable) {
            rowsSpinner.setValue(gridPanel.getGridRowsNumber());
            columnsSpinner.setValue(gridPanel.getGridColumnsNumber());
            mapGridChanged = true;
        }

        editingMode = enable;

        rowsSpinner.setEnabled(enable);
        columnsSpinner.setEnabled(enable);

        emptyCellButton.setEnabled(enable);
        wallCellButton.setEnabled(enable);
        obstacleCellButton.setEnabled(enable);
        exitCellButton.setEnabled(enable);
        personCellButton.setEnabled(enable);

        if (mainWindow != null) {
            mainWindow.setEditMode(enable);
            if(!enable) {
                gridPanel.getGrid().identifyExits();
                gridPanel.getGrid().calculatePotentials();
                gridPanel.getGrid().calculateBottleNecks();
            }
        }

    }//GEN-LAST:event_editingButtonActionPerformed

    private void rowsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rowsSpinnerStateChanged
        if (editingMode) {
            gridPanel.setGridSize(Integer.parseInt(rowsSpinner.getValue().toString()),
                    Integer.parseInt(columnsSpinner.getValue().toString()));
        }
    }//GEN-LAST:event_rowsSpinnerStateChanged

    private void columnsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_columnsSpinnerStateChanged
        if (editingMode) {
            gridPanel.setGridSize(Integer.parseInt(rowsSpinner.getValue().toString()),
                    Integer.parseInt(columnsSpinner.getValue().toString()));
        }
    }//GEN-LAST:event_columnsSpinnerStateChanged

    private void obstacleCellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obstacleCellButtonActionPerformed
        cellTypeSelected = Grid.OBSTACLE;
    }//GEN-LAST:event_obstacleCellButtonActionPerformed

    /**
     * Setting gridPanel, will not work without this.
     * @param panel
     */
    public void setGridPanel(GridPanel panel) {
        gridPanel = panel;
    }

    /**
     * Setting mainWindow, will not work without this.
     * @param window
     */
    public void setMainWindow(EwakuacjaView window) {
        mainWindow = window;
    }

    /**
     * Lets to check if editing mode is enabled.
     * @return true, if editing mode is enabled.
     */
    public boolean isEditingMode() {
        return editingMode;
    }

    /**
     * Exit from editing mode.
     */
    public void stopEditing() {
        editingButton.setSelected(false);
        editingButtonActionPerformed(null);
    }

    /**
     * Use this method to get type of cell selected.
     * @return selected cell type, according to values in Grid class.
     */
    public int getCellTypeSelected() {
        return cellTypeSelected;
    }

    /**
     * Method to get information if grid has been changed after last saving.
     * Precisely it checks if editMode has been enabled.
     * @return
     */
    public boolean getMapGridChanged() {
        return mapGridChanged;
    }

    /**
     * Sents information about changing grid after saving.
     * @param aFlag
     */
    public void setMapGridChanged(boolean aFlag) {
        mapGridChanged = aFlag;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup cellTypeButtons;
    private javax.swing.JSpinner columnsSpinner;
    private javax.swing.JCheckBox editingButton;
    private javax.swing.JRadioButton emptyCellButton;
    private javax.swing.JPanel emptyColorPanel;
    private javax.swing.JRadioButton exitCellButton;
    private javax.swing.JPanel exitColorPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton obstacleCellButton;
    private javax.swing.JPanel obstacleColorPanel;
    private javax.swing.JRadioButton personCellButton;
    private javax.swing.JPanel personColorPanel;
    private javax.swing.JSpinner rowsSpinner;
    private javax.swing.JRadioButton wallCellButton;
    private javax.swing.JPanel wallColorPanel;
    // End of variables declaration//GEN-END:variables
    int cellTypeSelected = Grid.EMPTY;
    GridPanel gridPanel;
    EwakuacjaView mainWindow = null;
    private boolean editingMode = false;
    private boolean mapGridChanged = false;
}
